from datetime import date

from sqlalchemy import inspect
from sqlmodel import Session, SQLModel, select

from app.budget.db import ensure_schema
from app.budget.models import Budget, Goal, Transaction
from tests.postgres import seed_accounts


def test_transaction_stores_reimburses_link(engine):
    """An incoming Zelle can point at the expense it reimburses."""
    with Session(engine) as s:
        seed_accounts(s)
        expense = Transaction(account_id=1, date=date(2026, 7, 1), name="Dinner",
                              amount=180.0, category="FOOD_AND_DRINK")
        s.add(expense); s.commit(); s.refresh(expense)
        zelle = Transaction(account_id=1, date=date(2026, 7, 2), name="Zelle from Ryan",
                            amount=-60.0, category="TRANSFER_IN",
                            reimburses_transaction_id=expense.id)
        s.add(zelle); s.commit(); s.refresh(zelle)
        assert zelle.reimburses_transaction_id == expense.id


def test_ensure_schema_adds_reimburses_column_to_old_db(postgres_engine_factory):
    """create_all() won't alter an existing table, so ensure_schema() must add the
    new column to a database created before this feature — without touching data."""
    eng = postgres_engine_factory()
    # Simulate a pre-feature database: the transaction table without the new column.
    with eng.begin() as conn:
        conn.exec_driver_sql(
            'CREATE TABLE "transaction" ('
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "plaid_transaction_id VARCHAR, account_id INTEGER NOT NULL, "
            "date DATE NOT NULL, name VARCHAR NOT NULL, merchant_name VARCHAR, "
            "amount DOUBLE PRECISION NOT NULL, category VARCHAR, user_category VARCHAR, "
            "pending BOOLEAN NOT NULL)"
        )
        conn.exec_driver_sql(
            'INSERT INTO "transaction" (account_id, date, name, amount, pending) '
            "VALUES (1, '2026-07-01', 'Old', 5.0, FALSE)"
        )

    ensure_schema(eng)

    with eng.connect() as conn:
        cols = {column["name"] for column in inspect(conn).get_columns("transaction")}
        assert "reimburses_transaction_id" in cols
        row = conn.exec_driver_sql(
            'SELECT name, reimburses_transaction_id FROM "transaction"'
        ).one()
        assert row[0] == "Old"        # existing data preserved
        assert row[1] is None         # new column defaults to NULL


def test_ensure_schema_is_idempotent(engine):
    """Running the migration when the column already exists is a no-op, not an error."""
    ensure_schema(engine)
    ensure_schema(engine)  # second run must not raise


def test_ensure_schema_adds_goal_icon_color_columns(postgres_engine_factory):
    eng = postgres_engine_factory()
    # Pre-feature goal table: no icon/color columns.
    with eng.begin() as conn:
        conn.exec_driver_sql(
            'CREATE TABLE "goal" ('
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "name VARCHAR NOT NULL, kind VARCHAR NOT NULL, "
            "target DOUBLE PRECISION, category VARCHAR, current DOUBLE PRECISION)"
        )
        conn.exec_driver_sql(
            'INSERT INTO "goal" (name, kind, target) VALUES (\'Reps\', \'numeric\', 100)'
        )
    SQLModel.metadata.create_all(eng)  # builds budgetrule etc.; skips existing goal
    ensure_schema(eng)
    with eng.connect() as conn:
        inspector = inspect(conn)
        gcols = {column["name"] for column in inspector.get_columns("goal")}
        assert {
            "icon",
            "color",
            "repeat_until_completed",
            "nudge_interval_minutes",
        } <= gcols
        row = conn.exec_driver_sql('SELECT name, icon, color FROM "goal"').one()
        assert row[0] == "Reps" and row[1] is None and row[2] is None  # data preserved, new cols NULL
        tables = set(inspector.get_table_names())
        assert "goalgroupsettings" in tables


def test_spending_goals_migrate_to_period_budgets_and_archive(engine):
    with Session(engine) as session:
        goal = Goal(name="Dining", kind="spend_cap", target=100, category="EATING_OUT", period="weekly")
        session.add(goal); session.commit(); session.refresh(goal)

    ensure_schema(engine)

    with Session(engine) as session:
        budget = session.exec(select(Budget)).one()
        migrated_goal = session.exec(select(Goal)).one()
        assert (budget.category, budget.monthly_limit, budget.period) == ("EATING_OUT", 100, "weekly")
        assert migrated_goal.archived_at is not None
